"""
GitGrind — Cheat sheet generator (endgame reward).
Categorizes all learned commands and saves a formatted text file.
"""
import os


CHEATSHEET_FILE = os.path.join(os.path.dirname(__file__), "git_cheatsheet.txt")


# ── Category Map ─────────────────────────────────────────
# Maps taught commands to cheat sheet categories.
# Keys MUST exactly match the strings used in commands_taught
# arrays across all level files.

category_map = {
    # Basics
    "git init": "Basics",
    "git status": "Basics",
    # Staging & Committing
    "git add <file>": "Staging & Committing",
    "git add .": "Staging & Committing",
    "git commit -m": "Staging & Committing",
    "git commit --amend": "Staging & Committing",
    # .gitignore
    ".gitignore": ".gitignore",
    "git rm --cached": ".gitignore",
    # Viewing Changes & History
    "git diff": "Viewing Changes & History",
    "git diff --staged": "Viewing Changes & History",
    "git log": "Viewing Changes & History",
    "git log --oneline": "Viewing Changes & History",
    "git log --oneline --graph": "Viewing Changes & History",
    "git log --stat": "Viewing Changes & History",
    "git log --author": "Viewing Changes & History",
    "git log --since": "Viewing Changes & History",
    "git log --grep": "Viewing Changes & History",
    "git log --graph": "Viewing Changes & History",
    # Branching
    "git branch <name>": "Branching",
    "git branch": "Branching",
    "git branch -a": "Branching",
    "git branch -d <name>": "Branching",
    "git branch -r": "Branching",
    "git switch <branch>": "Branching",
    "git switch -c <name>": "Branching",
    "git checkout <branch>": "Branching",
    "git checkout -b <name>": "Branching",
    # Merging
    "git merge <branch>": "Merging",
    "conflict resolution": "Merging",
    # Note: "git add <file>" already mapped in Staging & Committing
    # Remotes
    "git remote add origin <url>": "Remotes",
    "git remote -v": "Remotes",
    "git remote set-url": "Remotes",
    "git clone <url>": "Remotes",
    "git push -u origin main": "Remotes",
    "git push": "Remotes",
    "git push origin <branch>": "Remotes",
    "git push origin --delete <branch>": "Remotes",
    "git fetch origin": "Remotes",
    "git pull": "Remotes",
    "git pull origin main": "Remotes",
    # Undo & Restore
    "git restore <file>": "Undo & Restore",
    "git restore --staged <file>": "Undo & Restore",
    "git reset HEAD~1": "Undo & Restore",
    "git reset --soft HEAD~1": "Undo & Restore",
    "git reset --hard HEAD~1": "Undo & Restore",
    "git revert <hash>": "Undo & Restore",
    # Stash
    "git stash": "Stash",
    "git stash list": "Stash",
    "git stash pop": "Stash",
    "git stash apply": "Stash",
    "git stash drop": "Stash",
    # Reflog
    "git reflog": "Reflog",
    # Rebase
    "git rebase main": "Rebase",
    "git rebase -i HEAD~N": "Rebase",
    "git rebase --continue": "Rebase",
    "git rebase --abort": "Rebase",
    # Pro Moves
    "git cherry-pick <hash>": "Pro Moves",
    "git tag v1.0": "Pro Moves",
    "git tag -a v1.0 -m 'msg'": "Pro Moves",
    "git blame <file>": "Pro Moves",
    "git push --force-with-lease": "Pro Moves",
    "git config --global alias.st status": "Pro Moves",
}


# Category display order
CATEGORY_ORDER = [
    "Basics",
    "Staging & Committing",
    ".gitignore",
    "Viewing Changes & History",
    "Branching",
    "Merging",
    "Remotes",
    "Undo & Restore",
    "Stash",
    "Reflog",
    "Rebase",
    "Pro Moves",
]


def generate_cheatsheet(state):
    """Generate the cheat sheet reward file."""

    # Build categories from learned commands
    categories = {cat: [] for cat in CATEGORY_ORDER}
    categories["Other"] = []

    for cmd in state.data["commands_learned"]:
        cat = category_map.get(cmd, "Other")
        if cat not in categories:
            categories[cat] = []
        categories[cat].append(cmd)

    # Build output
    lines = []
    lines.append("=" * 60)
    lines.append("  GIT CHEAT SHEET — Generated by GitGrind")
    lines.append("=" * 60)
    lines.append("")

    # Stats
    lines.append(f"  Accuracy:         {state.accuracy}%")
    lines.append(f"  First-Try:        {state.first_try_accuracy}%")
    lines.append(f"  Commands typed:   {state.total_commands_typed}")
    lines.append(f"  Hints used:       {state.hints_used}")
    lines.append(f"  Time played:      {state.time_played_display}")
    lines.append("")
    lines.append("-" * 60)

    for cat in CATEGORY_ORDER:
        cmds = categories.get(cat, [])
        if not cmds:
            continue
        lines.append("")
        lines.append(f"  📂 {cat.upper()}")
        lines.append(f"  {'─' * 40}")
        for cmd in cmds:
            lines.append(f"    {cmd}")

    # Show "Other" if any unmapped commands exist
    other_cmds = categories.get("Other", [])
    if other_cmds:
        lines.append("")
        lines.append("  📂 OTHER")
        lines.append(f"  {'─' * 40}")
        for cmd in other_cmds:
            lines.append(f"    {cmd}")

    lines.append("")
    lines.append("=" * 60)
    lines.append("  Keep grinding. You've got this. 🚀")
    lines.append("=" * 60)

    with open(CHEATSHEET_FILE, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
