"""
GitGrind — Notebook export.
Saves the player's notebook (learned commands + explanations) as a .txt file.
"""
import os
from cheatsheet import category_map, CATEGORY_ORDER


NOTEBOOK_FILE = os.path.join(os.path.dirname(__file__), "git_notebook.txt")


def generate_notebook_txt(state):
    """
    Save the notebook entries to a formatted .txt file.
    Returns the path to the saved file.
    """
    entries = state.notebook_entries
    if not entries:
        return None

    # Group by category
    categorized = {cat: [] for cat in CATEGORY_ORDER}
    categorized["Other"] = []

    for cmd, data in entries.items():
        cat = category_map.get(cmd, "Other")
        if cat not in categorized:
            categorized[cat] = []
        categorized[cat].append((cmd, data))

    lines = []
    lines.append("=" * 60)
    lines.append("  GIT NOTEBOOK — Generated by GitGrind")
    lines.append("=" * 60)
    lines.append("")
    lines.append(f"  Commands learned: {len(entries)}")
    lines.append("")
    lines.append("-" * 60)

    for cat in CATEGORY_ORDER + ["Other"]:
        cmds = categorized.get(cat, [])
        if not cmds:
            continue

        lines.append("")
        lines.append(f"  📂 {cat.upper()}")
        lines.append(f"  {'─' * 50}")

        for cmd, data in cmds:
            lines.append("")
            lines.append(f"    ▸ {cmd}")
            if data.get("syntax"):
                lines.append(f"      Syntax: {data['syntax']}")
            if data.get("explanation"):
                for eline in data["explanation"].strip().split("\n"):
                    lines.append(f"      {eline}")
            if data.get("pro_tip"):
                lines.append(f"      💡 Tip: {data['pro_tip']}")

    lines.append("")
    lines.append("=" * 60)
    lines.append("  Keep grinding. You've got this. 🚀")
    lines.append("=" * 60)

    with open(NOTEBOOK_FILE, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    return NOTEBOOK_FILE
