"""
GitGrind — 5 Exercise Rounds (grinding sessions between levels).
"""
from content.models import Exercise, ExerciseRound


# ═══════════════════════════════════════════════════════════
#  EXERCISE ROUND 1 — Absolute Basics (after Level 3)
# ═══════════════════════════════════════════════════════════

EXERCISE_ROUND_1 = ExerciseRound(
    number=1,
    name="Absolute Basics",
    tagline="Levels 1-3. Lock init, add, commit, log into muscle memory.",
    pass_threshold=(12, 15),
    exercises=[
        # Rapid fire
        Exercise(type="rapid_fire", prompt="Initialize a repo.", answers=["git init"],
                 explanation="First command for any new project."),
        Exercise(type="rapid_fire", prompt="Check repo state.", answers=["git status"],
                 explanation="Your constant companion—run it before every add/commit."),
        Exercise(type="rapid_fire", prompt="Stage all files.", answers=["git add .", "git add -A"],
                 explanation="The dot stages everything. Check 'git status' first!"),
        Exercise(type="rapid_fire", prompt="Commit with message 'init'.",
                 answers=['git commit -m "init"', "git commit -m 'init'"],
                 explanation="Always include a meaningful message with -m."),
        Exercise(type="rapid_fire", prompt="View log.", answers=["git log", "git log --oneline"],
                 explanation="See your commit history. Press 'q' to exit."),
        Exercise(type="rapid_fire", prompt="Stage file 'app.py'.", answers=["git add app.py"],
                 explanation="Stage specific files for focused commits."),
        Exercise(type="rapid_fire", prompt="Compact log.", answers=["git log --oneline"],
                 explanation="One line per commit—much faster to scan."),
        # Fill blank
        Exercise(type="fill_blank", prompt="Complete the commit command.",
                 blank_template='git ____ -m "fix bug"', answers=["commit"],
                 explanation="'commit' saves staged changes as a snapshot."),
        Exercise(type="fill_blank", prompt="Complete the staging command.",
                 blank_template="git ____ .", answers=["add"],
                 explanation="'add' moves files to the staging area."),
        Exercise(type="fill_blank", prompt="Complete the command.",
                 blank_template="git ____ --oneline", answers=["log"],
                 explanation="'log' shows commit history."),
        # Multi-step
        Exercise(type="scenario", prompt="Create a repo, stage everything, commit with message 'first'. Write all commands separated by &&.",
                 answers=[
                     'git init && git add . && git commit -m "first"',
                     "git init && git add . && git commit -m 'first'",
                     "git init && git add -A && git commit -m 'first'",
                 ],
                 explanation="The complete starter workflow. Use && to chain commands."),
        # Reverse
        Exercise(type="reverse", prompt="What command produced this output?",
                 sim_output="Initialized empty Git repository in /project/.git/",
                 answers=["git init"],
                 explanation="Only 'git init' creates this message."),
        Exercise(type="reverse", prompt="What command produced this output?",
                 sim_output="[main (root-commit) a1b2c3d] initial commit\n 2 files changed, 15 insertions(+)",
                 answers=['git commit -m "initial commit"', "git commit -m 'initial commit'"],
                 explanation="This is the output format of 'git commit'."),
        # Error fix
        Exercise(type="error_fix", prompt="You got this error. What's wrong?",
                 error_output="fatal: not a git repository (or any of the parent directories): .git",
                 answers=["git init"],
                 hint="You haven't initialized a repo yet",
                 explanation="This error means no .git folder exists. Run 'git init' first."),
        Exercise(type="error_fix", prompt="You ran 'git commit' and got this. What did you forget?",
                 error_output='nothing added to commit but untracked files present (use "git add" to track)',
                 answers=["git add .", "git add <file>", "git add"],
                 explanation="You forgot to stage files. Commit only saves what's staged."),
    ],
)


# ═══════════════════════════════════════════════════════════
#  EXERCISE ROUND 2 — Solo Repo Mastery (after Level 6)
# ═══════════════════════════════════════════════════════════

EXERCISE_ROUND_2 = ExerciseRound(
    number=2,
    name="Solo Repo Mastery",
    tagline="Levels 1-6. Everything a solo developer needs.",
    pass_threshold=(12, 15),
    exercises=[
        Exercise(type="rapid_fire", prompt="Stage everything.", answers=["git add .", "git add -A"],
                 explanation="Quickest way to stage all changes at once."),
        Exercise(type="rapid_fire", prompt="Show unstaged changes.", answers=["git diff"],
                 explanation="Review what you changed before staging."),
        Exercise(type="rapid_fire", prompt="Show staged changes.", answers=["git diff --staged", "git diff --cached"],
                 explanation="Preview what's about to be committed."),
        Exercise(type="rapid_fire", prompt="View compact log.", answers=["git log --oneline"],
                 explanation="Most useful log format for daily work."),
        Exercise(type="rapid_fire", prompt="Log with graph.", answers=["git log --oneline --graph", "git log --graph"],
                 explanation="Visualize branch structure in the terminal."),
        Exercise(type="rapid_fire", prompt="Untrack a committed file 'debug.log' (keep on disk).",
                 answers=["git rm --cached debug.log"],
                 explanation="Fixes .gitignore mistakes without deleting the file."),
        Exercise(type="fill_blank", prompt="Search commits for 'fix'.",
                 blank_template='git log --____="fix"', answers=["grep"],
                 explanation="--grep searches commit messages for keywords."),
        Exercise(type="fill_blank", prompt="Filter log by author.",
                 blank_template='git log --____="Alice"', answers=["author"],
                 explanation="--author shows commits by a specific person."),
        Exercise(type="fill_blank", prompt="See what will be committed.",
                 blank_template="git diff --____", answers=["staged", "cached"],
                 explanation="--staged (or --cached) shows changes ready to commit."),
        Exercise(type="scenario",
                 prompt="Init repo, stage .gitignore, commit 'setup', then stage app.py, commit 'add app'. Separate commands with &&.\n(Assume files already exist.)",
                 answers=[
                     'git init && git add .gitignore && git commit -m "setup" && git add app.py && git commit -m "add app"',
                     "git init && git add .gitignore && git commit -m 'setup' && git add app.py && git commit -m 'add app'",
                     'git init && git add . && git commit -m "setup" && git add app.py && git commit -m "add app"',
                 ],
                 explanation="Multiple focused commits are better than one giant commit."),
        Exercise(type="reverse", prompt="What command produced this output?",
                 sim_output="diff --git a/app.py b/app.py\n--- a/app.py\n+++ b/app.py\n@@ -1 +1,2 @@\n+import sys",
                 answers=["git diff"],
                 explanation="This is the standard diff output format."),
        Exercise(type="reverse", prompt="What command produced this?",
                 sim_output="a1b2c3d fix login\ne4f5g6h add homepage\ni7j8k9l initial commit",
                 answers=["git log --oneline"],
                 explanation="Oneline format: hash + message, one per line."),
        Exercise(type="error_fix", prompt="You added '*.log' to .gitignore but 'git status' still shows 'debug.log' as tracked. Fix it.",
                 error_output="Changes not staged for commit:\n  modified: debug.log",
                 answers=["git rm --cached debug.log"],
                 explanation=".gitignore only affects untracked files. Already-tracked files need 'git rm --cached' to untrack."),
        Exercise(type="rapid_fire", prompt="Ignore pattern for .env files.", answers=[".env"],
                 explanation="Add this line to .gitignore to ignore environment files."),
        Exercise(type="rapid_fire", prompt="Log with file change stats.", answers=["git log --stat"],
                 explanation="Shows which files changed and how much in each commit."),
    ],
)


# ═══════════════════════════════════════════════════════════
#  EXERCISE ROUND 3 — Branch Warfare (after Level 10)
# ═══════════════════════════════════════════════════════════

EXERCISE_ROUND_3 = ExerciseRound(
    number=3,
    name="Branch Warfare",
    tagline="Levels 7-10. Branch operations should feel automatic.",
    pass_threshold=(12, 15),
    exercises=[
        Exercise(type="rapid_fire", prompt="Create branch 'feature-x'.", answers=["git branch feature-x"],
                 explanation="Creates the branch but doesn't switch to it."),
        Exercise(type="rapid_fire", prompt="Switch to 'feature-x'.", answers=["git switch feature-x", "git checkout feature-x"],
                 explanation="Moves you to the branch. All files change to match that branch."),
        Exercise(type="rapid_fire", prompt="Create + switch to 'hotfix'.", answers=["git switch -c hotfix", "git checkout -b hotfix"],
                 explanation="One-command shortcut for create + switch."),
        Exercise(type="rapid_fire", prompt="Switch to main.", answers=["git switch main", "git checkout main"],
                 explanation="Return to the main branch."),
        Exercise(type="rapid_fire", prompt="Merge 'hotfix' into current branch.", answers=["git merge hotfix"],
                 explanation="Brings hotfix's commits into your current branch."),
        Exercise(type="rapid_fire", prompt="Delete merged branch 'hotfix'.", answers=["git branch -d hotfix"],
                 explanation="Clean up after merging. The -d is safe—won't delete unmerged branches."),
        Exercise(type="rapid_fire", prompt="List all branches.", answers=["git branch"],
                 explanation="Shows branches. The * marks which one you're on."),
        Exercise(type="rapid_fire", prompt="View merge graph.", answers=["git log --oneline --graph", "git log --oneline --graph --all"],
                 explanation="Visualizes how branches split and merged."),
        Exercise(type="fill_blank", prompt="Create and switch in one command.",
                 blank_template="git switch ____ new-feature", answers=["-c"],
                 explanation="-c means 'create'. Combines branch creation and switching."),
        Exercise(type="fill_blank", prompt="Delete a merged branch.",
                 blank_template="git branch ____ old-branch", answers=["-d"],
                 explanation="-d is the safe delete. Use -D to force-delete unmerged branches."),
        Exercise(type="scenario",
                 prompt="Create 'feature-auth', switch to it, then switch back to main, merge it, and delete it. All commands with &&.",
                 answers=[
                     "git switch -c feature-auth && git switch main && git merge feature-auth && git branch -d feature-auth",
                     "git checkout -b feature-auth && git checkout main && git merge feature-auth && git branch -d feature-auth",
                 ],
                 explanation="The complete feature branch workflow in one line."),
        Exercise(type="error_fix", prompt="You tried to delete a branch and got this error. What's the option to force-delete it?",
                 error_output="error: The branch 'experiment' is not fully merged.\nIf you are sure you want to delete it, run 'git branch -D experiment'.",
                 answers=["git branch -D experiment"],
                 explanation="Git protects you from deleting unmerged work. -D (capital D) overrides this safety."),
        Exercise(type="scenario", prompt="After resolving a merge conflict, what TWO commands finish the merge?",
                 answers=["git add . && git commit", "git add <file> && git commit"],
                 explanation="Stage the resolved files, then commit to complete the merge."),
        Exercise(type="reverse", prompt="What command produced this?",
                 sim_output="  feature-login\n* main\n  hotfix",
                 answers=["git branch"],
                 explanation="'git branch' lists branches. The * shows your current branch."),
        Exercise(type="rapid_fire", prompt="Stage resolved conflict file 'app.py'.", answers=["git add app.py"],
                 explanation="After resolving conflicts, stage the fixed files before committing."),
    ],
)


# ═══════════════════════════════════════════════════════════
#  EXERCISE ROUND 4 — Remote Ops (after Level 14)
# ═══════════════════════════════════════════════════════════

EXERCISE_ROUND_4 = ExerciseRound(
    number=4,
    name="Remote Ops",
    tagline="Levels 11-14. Cloud operations need to be seamless.",
    pass_threshold=(12, 15),
    exercises=[
        Exercise(type="rapid_fire", prompt="Add remote 'origin'.",
                 answers=["git remote add origin <url>", "git remote add origin https://github.com/user/repo.git"],
                 explanation="Connects your local repo to GitHub/GitLab. Run once per repo."),
        Exercise(type="rapid_fire", prompt="Verify remotes.", answers=["git remote -v"],
                 explanation="Shows configured remotes with their URLs. -v is essential."),
        Exercise(type="rapid_fire", prompt="Clone a repo.",
                 answers=["git clone <url>", "git clone https://github.com/user/repo.git"],
                 explanation="Downloads complete repo with history. Auto-sets up 'origin'."),
        Exercise(type="rapid_fire", prompt="First push to origin main.", answers=["git push -u origin main"],
                 explanation="-u sets upstream tracking. Only needed on first push per branch."),
        Exercise(type="rapid_fire", prompt="Push (upstream set).", answers=["git push"],
                 explanation="After -u, plain 'git push' knows where to go."),
        Exercise(type="rapid_fire", prompt="Fetch from remote.", answers=["git fetch", "git fetch origin"],
                 explanation="Downloads commits without merging. Safe to run anytime."),
        Exercise(type="rapid_fire", prompt="Pull remote changes.", answers=["git pull", "git pull origin main"],
                 explanation="Fetch + merge in one command. Quick sync."),
        Exercise(type="rapid_fire", prompt="Push branch 'feature-x' to remote.", answers=["git push origin feature-x"],
                 explanation="Shares your feature branch for Pull Requests or collaboration."),
        Exercise(type="rapid_fire", prompt="Delete remote branch 'stale'.", answers=["git push origin --delete stale"],
                 explanation="Cleans up merged branches on the server."),
        Exercise(type="rapid_fire", prompt="List remote branches.", answers=["git branch -r"],
                 explanation="-r shows branches that exist on the remote server."),
        Exercise(type="fill_blank", prompt="Set upstream on first push.",
                 blank_template="git push ____ origin main", answers=["-u"],
                 explanation="-u links your local branch to the remote one."),
        Exercise(type="fill_blank", prompt="Download without merging.",
                 blank_template="git ____ origin", answers=["fetch"],
                 explanation="Fetch is safe—it downloads but doesn't change your files."),
        Exercise(type="scenario",
                 prompt="Clone a repo, create branch 'fix', push the branch, then delete the remote branch. All with &&.\n(Assume you've already committed on the branch.)",
                 answers=[
                     'git clone <url> && git switch -c fix && git push origin fix && git push origin --delete fix',
                     'git clone <url> && git checkout -b fix && git push origin fix && git push origin --delete fix',
                 ],
                 explanation="Complete remote workflow: clone, branch, share, cleanup."),
        Exercise(type="error_fix", prompt="Push rejected. What do you do first?",
                 error_output="! [rejected]        main -> main (non-fast-forward)\nhint: Updates were rejected because the remote contains work you don't have.",
                 answers=["git pull", "git pull origin main"],
                 explanation="Someone pushed while you were working. Pull their changes first, then push again."),
        Exercise(type="reverse", prompt="What command produced this?",
                 sim_output="Branch 'main' set up to track remote branch 'main' from 'origin'.",
                 answers=["git push -u origin main"],
                 explanation="This message confirms upstream tracking was set with -u."),
    ],
)


# ═══════════════════════════════════════════════════════════
#  EXERCISE ROUND 5 — The Final Grind (after Level 20)
# ═══════════════════════════════════════════════════════════

EXERCISE_ROUND_5 = ExerciseRound(
    number=5,
    name="The Final Grind",
    tagline="ALL 20 levels. The ultimate test.",
    pass_threshold=(20, 25),
    exercises=[
        Exercise(type="rapid_fire", prompt="Init a repo.", answers=["git init"],
                 explanation="Still the first command for every project."),
        Exercise(type="rapid_fire", prompt="Stage all.", answers=["git add .", "git add -A"],
                 explanation="Stage everything at once."),
        Exercise(type="rapid_fire", prompt="Commit with 'done'.",
                 answers=['git commit -m "done"', "git commit -m 'done'"],
                 explanation="Commit your staged changes."),
        Exercise(type="rapid_fire", prompt="Create + switch to 'feature'.", answers=["git switch -c feature", "git checkout -b feature"],
                 explanation="One-command branch creation and switch."),
        Exercise(type="rapid_fire", prompt="Merge 'feature'.", answers=["git merge feature"],
                 explanation="Bring feature commits into your current branch."),
        Exercise(type="rapid_fire", prompt="Push to origin main.", answers=["git push", "git push origin main"],
                 explanation="Upload commits to remote."),
        Exercise(type="rapid_fire", prompt="Pull from remote.", answers=["git pull", "git pull origin main"],
                 explanation="Download and merge remote changes."),
        Exercise(type="rapid_fire", prompt="Stash current work.", answers=["git stash"],
                 explanation="Save uncommitted changes temporarily."),
        Exercise(type="rapid_fire", prompt="Pop stashed work.", answers=["git stash pop"],
                 explanation="Restore stashed changes and remove from stash."),
        Exercise(type="rapid_fire", prompt="Rebase onto main.", answers=["git rebase main"],
                 explanation="Replay your commits on top of main."),
        Exercise(type="rapid_fire", prompt="Interactive rebase last 3.", answers=["git rebase -i HEAD~3"],
                 explanation="Edit, squash, or reorder the last 3 commits."),
        Exercise(type="rapid_fire", prompt="View reflog.", answers=["git reflog"],
                 explanation="See every HEAD movement—your safety net."),
        Exercise(type="rapid_fire", prompt="Cherry-pick commit abc123.", answers=["git cherry-pick abc123"],
                 explanation="Copy one specific commit to current branch."),
        Exercise(type="rapid_fire", prompt="Tag as v1.0.", answers=["git tag v1.0"],
                 explanation="Mark this commit as a release."),
        Exercise(type="rapid_fire", prompt="Blame file 'app.py'.", answers=["git blame app.py"],
                 explanation="See who last modified each line."),
        Exercise(type="rapid_fire", prompt="Soft reset last commit.", answers=["git reset --soft HEAD~1"],
                 explanation="Undo commit but keep changes staged."),
        Exercise(type="rapid_fire", prompt="Hard reset last commit.", answers=["git reset --hard HEAD~1"],
                 explanation="Undo commit AND delete all changes permanently."),
        Exercise(type="rapid_fire", prompt="Revert commit xyz789.", answers=["git revert xyz789"],
                 explanation="Create new commit that undoes an old one."),
        Exercise(type="rapid_fire", prompt="Safe force push.", answers=["git push --force-with-lease"],
                 explanation="Force push with safety check."),
        Exercise(type="rapid_fire", prompt="Amend last commit message.",
                 answers=["git commit --amend", 'git commit --amend -m "<message>"'],
                 explanation="Fix the most recent commit."),
        # Multi-step workflows
        Exercise(type="scenario",
                 prompt="Stash → switch to main → pull → switch back to feature → pop stash → rebase onto main. All with &&.",
                 answers=[
                     "git stash && git switch main && git pull && git switch feature && git stash pop && git rebase main",
                     "git stash && git checkout main && git pull && git checkout feature && git stash pop && git rebase main",
                 ],
                 explanation="Advanced workflow combining stash, pull, and rebase."),
        Exercise(type="scenario",
                 prompt="Recover from an accidental 'git reset --hard HEAD~2'. What 2 commands? (separated by &&)",
                 answers=["git reflog && git reset --hard <hash>"],
                 explanation="Reflog shows lost commits. Reset to the hash to recover."),
        Exercise(type="error_fix", prompt="You're mid-rebase and hit a conflict. After resolving, what continues the rebase?",
                 error_output="CONFLICT (content): Merge conflict in app.py\nerror: could not apply abc1234\nhint: Resolve all conflicts manually, then run \"git rebase --continue\".",
                 answers=["git rebase --continue"],
                 explanation="After resolving conflicts during rebase, --continue proceeds."),
        Exercise(type="fill_blank", prompt="Abort a messy rebase.",
                 blank_template="git rebase --____", answers=["abort"],
                 explanation="--abort cancels the rebase and restores original state."),
        Exercise(type="fill_blank", prompt="Continue rebase after fix.",
                 blank_template="git rebase --____", answers=["continue"],
                 explanation="--continue resumes rebase after resolving conflicts."),
    ],
)


# ═══════════════════════════════════════════════════════════
#  EXERCISE ROUND 6 — Retention Sprint I (mixed core review)
# ═══════════════════════════════════════════════════════════

EXERCISE_ROUND_6 = ExerciseRound(
    number=6,
    name="Retention Sprint I",
    tagline="Spaced repetition for the most-used commands (Levels 1-14).",
    pass_threshold=(14, 18),
    exercises=[
        Exercise(type="rapid_fire", prompt="Check repo state.", answers=["git status"],
                 explanation="Most-used Git command. Use constantly."),
        Exercise(type="rapid_fire", prompt="Initialize a repo.", answers=["git init"],
                 explanation="Start tracking a new project."),
        Exercise(type="rapid_fire", prompt="Stage app.py.", answers=["git add app.py"],
                 explanation="Stage specific files for clean commits."),
        Exercise(type="rapid_fire", prompt="Stage everything.", answers=["git add .", "git add -A"],
                 explanation="Stage all changes at once."),
        Exercise(type="rapid_fire", prompt="Commit with message 'savepoint'.",
                 answers=['git commit -m "savepoint"', "git commit -m 'savepoint'"],
                 explanation="Frequent everyday commit flow."),
        Exercise(type="rapid_fire", prompt="Show compact history.", answers=["git log --oneline"],
                 explanation="Quick commit overview."),
        Exercise(type="rapid_fire", prompt="Show unstaged diff.", answers=["git diff"],
                 explanation="Review before staging."),
        Exercise(type="rapid_fire", prompt="Create branch feature/payments.", answers=["git branch feature/payments"],
                 explanation="Branch creation without switching."),
        Exercise(type="rapid_fire", prompt="Create and switch to feature/payments.", answers=["git switch -c feature/payments", "git checkout -b feature/payments"],
                 explanation="Common feature-branch start."),
        Exercise(type="rapid_fire", prompt="Merge feature/payments into current branch.", answers=["git merge feature/payments"],
                 explanation="Bring feature commits into branch."),
        Exercise(type="rapid_fire", prompt="Show remotes with URLs.", answers=["git remote -v"],
                 explanation="Verify remote wiring."),
        Exercise(type="rapid_fire", prompt="First push of main with upstream.", answers=["git push -u origin main"],
                 explanation="One-time upstream setup."),
        Exercise(type="rapid_fire", prompt="Download remote commits without merge.", answers=["git fetch", "git fetch origin"],
                 explanation="Safe sync operation."),
        Exercise(type="rapid_fire", prompt="Fetch and merge in one command.", answers=["git pull", "git pull origin main"],
                 explanation="Convenient sync when safe."),
        Exercise(type="scenario", prompt="Fix wrong remote URL for origin to https://github.com/team/app.git.",
                 answers=["git remote set-url origin https://github.com/team/app.git"],
                 explanation="Repair remote target when URL changes."),
        Exercise(type="reverse", prompt="What command produced this output?",
                 sim_output="Branch 'main' set up to track remote branch 'main' from 'origin'.",
                 answers=["git push -u origin main"],
                 explanation="This message appears on first upstream push."),
        Exercise(type="error_fix", prompt="Push rejected (non-fast-forward). What first?",
                 error_output="! [rejected] main -> main (non-fast-forward)",
                 answers=["git pull", "git pull origin main"],
                 explanation="Sync remote changes before pushing again."),
        Exercise(type="fill_blank", prompt="Delete merged branch safely.",
                 blank_template="git branch ____ old-feature", answers=["-d"],
                 explanation="Safe deletion for merged branch."),
    ],
)


# ═══════════════════════════════════════════════════════════
#  EXERCISE ROUND 7 — Retention Marathon (full mixed review)
# ═══════════════════════════════════════════════════════════

EXERCISE_ROUND_7 = ExerciseRound(
    number=7,
    name="Retention Marathon",
    tagline="Spaced repetition across basics, remotes, and advanced repair commands.",
    pass_threshold=(16, 20),
    exercises=[
        Exercise(type="rapid_fire", prompt="Unstage app.py but keep edits.", answers=["git restore --staged app.py"],
                 explanation="Moves from staged to modified."),
        Exercise(type="rapid_fire", prompt="Undo last commit, keep changes staged.", answers=["git reset --soft HEAD~1"],
                 explanation="Clean fix for commit sequencing."),
        Exercise(type="rapid_fire", prompt="Safely undo commit abc1234.", answers=["git revert abc1234"],
                 explanation="Creates inverse commit without rewriting history."),
        Exercise(type="rapid_fire", prompt="Temporarily store uncommitted work.", answers=["git stash"],
                 explanation="Quick context switch."),
        Exercise(type="rapid_fire", prompt="Bring stashed work back and drop stash.", answers=["git stash pop"],
                 explanation="Restore and remove in one command."),
        Exercise(type="rapid_fire", prompt="View reflog.", answers=["git reflog"],
                 explanation="Recovery safety net."),
        Exercise(type="rapid_fire", prompt="Continue a rebase after conflict resolution.", answers=["git rebase --continue"],
                 explanation="Standard rebase conflict flow."),
        Exercise(type="rapid_fire", prompt="Abort current rebase.", answers=["git rebase --abort"],
                 explanation="Return to pre-rebase state."),
        Exercise(type="rapid_fire", prompt="Cherry-pick commit f00ba12.", answers=["git cherry-pick f00ba12"],
                 explanation="Apply a single commit only."),
        Exercise(type="rapid_fire", prompt="Create annotated tag v2.1 with message 'release'.",
                 answers=['git tag -a v2.1 -m "release"', "git tag -a v2.1 -m 'release'"],
                 explanation="Release marker with metadata."),
        Exercise(type="rapid_fire", prompt="Safely force push rewritten history.", answers=["git push --force-with-lease"],
                 explanation="Protects teammates' work."),
        Exercise(type="rapid_fire", prompt="Inspect commit c0ffee1 with patch.", answers=["git show c0ffee1"],
                 explanation="Single-commit inspection."),
        Exercise(type="rapid_fire", prompt="Find ""auth"" in tracked files.", answers=['git grep "auth"', "git grep 'auth'", "git grep auth"],
                 explanation="Fast repo search."),
        Exercise(type="rapid_fire", prompt="Compare release/v2 to main.", answers=["git diff main..release/v2"],
                 explanation="Branch comparison before release."),
        Exercise(type="rapid_fire", prompt="Fetch and prune stale remote refs.", answers=["git fetch --prune"],
                 explanation="Keep remote-tracking list clean."),
        Exercise(type="rapid_fire", prompt="Squash merge feature/cleanup.", answers=["git merge --squash feature/cleanup"],
                 explanation="One clean commit from many."),
        Exercise(type="scenario", prompt="You need to locate regression commit quickly. Start bisect and mark current as bad.",
                 answers=["git bisect start && git bisect bad"],
                 explanation="Binary-search bug hunting start."),
        Exercise(type="rapid_fire", prompt="Exit bisect when done.", answers=["git bisect reset"],
                 explanation="Restores original HEAD."),
        Exercise(type="scenario", prompt="After pushing feature branch, what team action comes next?",
                 answers=["open pull request", "open a pull request", "create pull request", "create a pull request"],
                 explanation="Branch -> PR -> review -> merge."),
        Exercise(type="fill_blank", prompt="Track file history through renames.",
                 blank_template="git log ____ app.py", answers=["--follow"],
                 explanation="Keeps file history connected across rename."),
    ],
)


ALL_EXERCISE_ROUNDS = {
    1: EXERCISE_ROUND_1,
    2: EXERCISE_ROUND_2,
    3: EXERCISE_ROUND_3,
    4: EXERCISE_ROUND_4,
    5: EXERCISE_ROUND_5,
    6: EXERCISE_ROUND_6,
    7: EXERCISE_ROUND_7,
}
